name = "forceghostwriter"
license = "MIT"
licenselink = "https://github.com/mpirnat/forceghostwriter/blob/master/LICENSE.md"
description = "A fork of simple AJAX driven theme for the Ghost blogging platform ported to Hugo, further tweaked"
homepage = "https://github.com/mpirnat/forceghostwriter"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]
min_version = "0.60"

[author]
    name = "Mike Pirnat"
    homepage = "https://github.com/mpirnat"

[original]
    author = "Juraj Bubniak"
    homepage = "https://github.com/jbub"
    repo = "https://github.com/jbub/ghostwriter"